services:
  user_db:
    image: postgres:17-alpine
    container_name: user_db
    environment:
      POSTGRES_USER: ${USER_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${USER_DB_NAME:-user_db}
    ports:
      - '${USER_DB_PORT:-5432}:5432'
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  user_db_data:
    name: user_db_data
