name: Pull request workflow

# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --no-progress

      - name: Install user-service dependencies
        working-directory: services/user-service
        run: npm ci --no-progress

      - name: Run linter
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --no-progress

      - name: Install user-service dependencies
        working-directory: services/user-service
        run: npm ci --no-progress

      - name: Run build
        run: npm run build

  test:
    needs: [lint, build]
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MIGRATE: 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci --no-progress

      - name: Install user-service dependencies
        working-directory: services/user-service
        run: npm ci --no-progress

      - name: Start database
        run: docker compose up -d

      - name: Run tests
        run: npm run test
